Add runtime version checking
Allow pypdu users to specify a required pypdu version at runtime.

e.g.,

 import pypdu
 pypdu.require(0, 0, 12)

If the installed version of pypdu is too old, this will raise an
exception:

 pypdu.require(7, 8, 9)
 RuntimeError: Current pypdu version 0.0.12a3 does not meet required 7.8.9